<?php
namespace models;

use lib\App;

/**
 * Class User
 * @package models
 */
class User extends Model
{
    /**
     * @var string
     */
    public $username;
    /**
     * @var string
     */
    public $password;


    /**
     * @return bool
     * @throws \Exception
     */
    public function save()
    {
        if(!$this->username || !$this->password){
            throw new \Exception("Задайте логин и пароль для пользователя", 500);
        }

        if($recipe = self::findOne(['username' => $this->username])){
            throw new \Exception("Пользователь с таким именем уже существует", 500);
        }

        $this->password = md5($this->password);
        return parent::save(); // TODO: Change the autogenerated stub
    }

}
